#!/bin/bash

echo "======================================"
echo "🚀 PUSH VERS GITHUB"
echo "======================================"
echo ""
echo "Repository: https://github.com/salahkhalfi/igp-maintenance.git"
echo "Branche: main"
echo "Commits à pousser: 90"
echo "Tags à pousser: 7"
echo ""
echo "======================================"
echo "📋 INSTRUCTIONS"
echo "======================================"
echo ""
echo "Le repository est VIDE, nous allons faire un force push."
echo ""
echo "Option 1 - Avec Personal Access Token:"
echo "----------------------------------------"
echo "git push -f https://TOKEN@github.com/salahkhalfi/igp-maintenance.git main --tags"
echo ""
echo "Remplacez TOKEN par votre token GitHub"
echo "Créez un token sur: https://github.com/settings/tokens"
echo ""
echo "Option 2 - Avec gh CLI:"
echo "----------------------------------------"
echo "gh auth login"
echo "git push -f origin main --tags"
echo ""
echo "Option 3 - Configuration manuelle:"
echo "----------------------------------------"
echo "git config credential.helper store"
echo "git push -f origin main --tags"
echo "(Vous serez invité à entrer username et token)"
echo ""
echo "======================================"
echo "📊 VÉRIFICATION PRÉ-PUSH"
echo "======================================"
echo ""

echo "✅ Remote configuré:"
git remote -v

echo ""
echo "✅ Derniers commits (5):"
git log --oneline -5

echo ""
echo "✅ Tags disponibles:"
git tag -l

echo ""
echo "✅ Statut du repository:"
git status --short

echo ""
echo "======================================"
echo "🎯 COMMANDE RECOMMANDÉE"
echo "======================================"
echo ""
echo "Si vous avez un Personal Access Token, utilisez:"
echo ""
echo "cd /home/user/webapp"
echo "git push -f https://VOTRE_TOKEN@github.com/salahkhalfi/igp-maintenance.git main --tags"
echo ""
echo "======================================"

