#!/bin/bash

echo "======================================"
echo "🔧 MISE À JOUR DESCRIPTION GITHUB"
echo "======================================"
echo ""
echo "Repository: salahkhalfi/igp-maintenance"
echo ""
echo "Pour ajouter la description et le site web:"
echo ""
echo "1. Allez sur: https://github.com/salahkhalfi/igp-maintenance"
echo ""
echo "2. Cliquez sur l'icône ⚙️ (à côté de 'About' en haut à droite)"
echo ""
echo "3. Dans 'Description', collez:"
echo "   🔧 Système de Gestion de Maintenance Industrielle - Application Kanban avec React, Hono, Cloudflare Pages, D1, et R2"
echo ""
echo "4. Dans 'Website', collez:"
echo "   https://5e61f01a.webapp-7t8.pages.dev"
echo ""
echo "5. Cochez 'Use your GitHub Pages website'"
echo ""
echo "6. Dans 'Topics', ajoutez:"
echo "   cloudflare-pages, hono, react, maintenance, kanban, d1-database, r2-storage, typescript"
echo ""
echo "7. Cliquez 'Save changes'"
echo ""
echo "======================================"

